package exception;

public class lab3 {
    public static void main(String[] args) {
        //1
        /*
        try{
            System.out.println("Statement1");
            System.out.println("Statement2");
            System.out.println("Statement3");
        }
        catch (ArithmeticException ex){}
        catch (RuntimeException ex){}
        finally{System.out.println("statement4");}
        System.out.println("statement5");

         */
        //2
        /* //145
        try{
            System.out.println("Statement1");
            System.out.println(1/0);
            System.out.println("Statement3");
        }
        catch (ArithmeticException ex){}
        catch (RuntimeException ex){}
        finally{System.out.println("statement4");}
        System.out.println("statement5");
         */ //145
    }
}
